Repository VolleyMate/volleymate, pull requests merged in 2023-03, with the labels that each got.

#13 feature #2: Crear entidad Partido
  src/main/java/org/springframework/samples/petclinic/partido/Partido.java
Labels: enhancement

#17 feature #16: Relación Jugador-Partido
  src/main/java/org/springframework/samples/petclinic/jugador/Jugador.java
  src/main/java/org/springframework/samples/petclinic/partido/Partido.java
Labels: feat

#18 Task004 realizada
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorController.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorRepository.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorService.java
  src/test/java/org/springframework/samples/petclinic/jugador/JugadorControllerTests.java
Labels: enhancement

#38 feature #10: Detalles de partido
  src/main/java/org/springframework/samples/petclinic/partido/PartidoController.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoRepository.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoService.java
Labels: feat

#41 feature #8: Solicitud
  src/main/java/org/solicitud/EstadoSolicitud.java
  src/main/java/org/solicitud/Solicitud.java
Labels: feat

#42 Task 007
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorController.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorRepository.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorService.java
  src/main/java/org/springframework/samples/petclinic/jugador/exceptions/YaUnidoException.java
  src/main/java/org/springframework/samples/petclinic/partido/Partido.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoRepository.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoService.java
Labels: feat

#40 feature #9: Ver mis partidos jugador implementado
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorController.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorRepository.java
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorService.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoController.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoService.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/jugador/misPartidos.jsp
Labels: feat

#57 #11 Ver Partidos Creados
  src/main/java/org/springframework/samples/petclinic/jugador/JugadorController.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoRepository.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoService.java
Labels: feat

#50 Feature #5 Creación de Partidos
  src/main/java/org/springframework/samples/petclinic/partido/PartidoController.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoRepository.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoService.java
Labels: feat

#61 Task 012: ver solicitudes de un partido
  src/main/java/org/springframework/samples/petclinic/partido/Partido.java
  src/main/java/org/springframework/samples/petclinic/partido/PartidoController.java
  src/main/java/org/springframework/samples/petclinic/solicitud/Solicitud.java
  src/main/java/org/springframework/samples/petclinic/solicitud/SolicitudRepository.java
  src/main/java/org/springframework/samples/petclinic/solicitud/SolicitudService.java
Labels: enhancement

#65 refactor #29: Añadir atributos a Entidad Partido
  src/main/java/org/springframework/samples/volleymate/partido/Partido.java
  src/main/java/org/springframework/samples/volleymate/partido/Sexo.java
  src/main/java/org/springframework/samples/volleymate/partido/Tipo.java
  src/main/resources/db/hsqldb/data.sql
Labels: enhancement

#72 doc #71: Modelo de datos actualizado
  src/main/resources/diagram/ispp.drawio
Labels: documentation

#95 Fix #4: Arreglado de Crear Partido
  src/main/java/org/springframework/samples/volleymate/partido/Partido.java
  src/main/java/org/springframework/samples/volleymate/partido/PartidoController.java
  src/main/webapp/WEB-INF/jsp/partidos/crearPartido.jsp
Labels: bug

#102 Minor fixes
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
  src/main/java/org/springframework/samples/volleymate/solicitud/Solicitud.java
  src/main/java/org/springframework/samples/volleymate/user/User.java
  src/main/webapp/WEB-INF/jsp/jugadores/editarPerfil.jsp
  src/main/webapp/WEB-INF/jsp/partidos/partidoDetails.jsp
Labels: bug

#121 Entidad Mensaje y sus relaciones implementada
  src/main/java/org/springframework/samples/volleymate/mensaje/Mensaje.java
  src/main/java/org/springframework/samples/volleymate/partido/Partido.java
Labels: enhancement

#122 Filtrar partidos por tipo
  src/main/java/org/springframework/samples/volleymate/partido/PartidoController.java
  src/main/java/org/springframework/samples/volleymate/partido/PartidoRepository.java
  src/main/java/org/springframework/samples/volleymate/partido/PartidoService.java
Labels: enhancement

#125 Task 043
  src/main/java/org/springframework/samples/volleymate/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorRepository.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorService.java
  src/main/java/org/springframework/samples/volleymate/partido/PartidoController.java
Labels: enhancement

#127 feature #52: Pagos con volleys
  src/main/java/org/springframework/samples/volleymate/jugador/Jugador.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
  src/main/resources/db/hsqldb/data.sql
Labels: enhancement, feat

#149 feature #104: fix valoracion
  src/main/java/org/springframework/samples/volleymate/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
  src/main/java/org/springframework/samples/volleymate/valoracion/ValoracionController.java
  src/main/webapp/WEB-INF/jsp/jugadores/detallesJugador.jsp
  src/main/webapp/WEB-INF/jsp/valoraciones/crearValoracion.jsp
Labels: bug

#150 feature #134: Vista filtrado
  src/main/java/org/springframework/samples/volleymate/partido/PartidoController.java
  src/main/java/org/springframework/samples/volleymate/partido/PartidoService.java
  src/main/webapp/WEB-INF/jsp/partidos/listaPartidos.jsp
  src/main/webapp/WEB-INF/jsp/partidos/listaPartidosFiltrados.jsp
Labels: enhancement

#161 Task 056: actualizada a responsive la página de inicio
  src/main/webapp/WEB-INF/jsp/welcome.jsp
Labels: feat
