Repository VolleyMate/volleymate, pull requests merged in 2023-04, with the labels that each got.

#177 Task 068
  src/main/resources/application.properties
Labels: bug

#180 Task 068
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
  src/main/java/org/springframework/samples/volleymate/partido/PartidoController.java
  src/main/webapp/WEB-INF/jsp/jugadores/misPartidos.jsp
  src/main/webapp/WEB-INF/jsp/jugadores/notificacionesJugador.jsp
  src/main/webapp/WEB-INF/jsp/partidos/listaPartidos.jsp
Labels: enhancement, feat

#181 feature #69: Volleys semanales
  src/main/java/org/springframework/samples/volleymate/VolleyMateApplication.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorService.java
Labels: enhancement

#191 fix #179: fixing frontend
  src/main/webapp/WEB-INF/jsp/jugadores/misPartidos.jsp
  src/main/webapp/WEB-INF/jsp/partidos/listaPartidos.jsp
Labels: enhancement

#205 feature #204: Vista de Solicitud de Centro DONE
  src/main/java/org/springframework/samples/volleymate/centro/CentroController.java
  src/main/webapp/WEB-INF/jsp/centros/solicitudCentro.jsp
Labels: feat

#203 feature #200: Vista de Solicitar Centro DONE
  src/main/java/org/springframework/samples/volleymate/centro/CentroController.java
Labels: feat

#210 feature #208: responsive mis partidos y banner
  src/main/resources/banner.txt
  src/main/webapp/WEB-INF/jsp/jugadores/misPartidos.jsp
Labels: enhancement

#222 feature #215: Botón eliminar centro
  src/main/java/org/springframework/samples/volleymate/centro/CentroController.java
  src/main/webapp/WEB-INF/jsp/centros/centroDetails.jsp
  src/main/webapp/WEB-INF/jsp/centros/listaCentros.jsp
Labels: enhancement

#232 feature #231: Filtro de partidos arreglado
  src/main/java/org/springframework/samples/volleymate/partido/PartidoService.java
Labels: bug, enhancement

#233 Task 096
  pom.xml
  src/main/java/org/springframework/samples/volleymate/centro/Centro.java
  src/main/java/org/springframework/samples/volleymate/centro/CentroController.java
  src/main/java/org/springframework/samples/volleymate/configuration/MailConfig.java
  src/main/java/org/springframework/samples/volleymate/jugador/EmailService.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorService.java
  src/main/resources/application.properties
  src/main/resources/db/hsqldb/data.sql
Labels: enhancement

#251 Task 103
  src/main/java/org/springframework/samples/volleymate/centro/CentroController.java
  src/main/java/org/springframework/samples/volleymate/partido/Partido.java
Labels: feat

#248 Task 101
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorService.java
  src/main/java/org/springframework/samples/volleymate/user/UserService.java
Labels: enhancement

#265 Task 094
  src/main/java/org/springframework/samples/volleymate/jugador/JugadorController.java
Labels: enhancement

#271 Task 108
  src/main/webapp/WEB-INF/jsp/centros/editarCentro.jsp
  src/main/webapp/WEB-INF/jsp/partidos/editarPartido.jsp
  src/main/webapp/WEB-INF/jsp/partidos/partidoDetails.jsp
Labels: enhancement

#275 Task #260: Vista Filtrado por Valoracion Media
  src/main/java/org/springframework/samples/volleymate/jugador/Jugador.java
  src/main/webapp/WEB-INF/jsp/jugadores/detallesJugador.jsp
  src/main/webapp/WEB-INF/jsp/jugadores/listaJugadores.jsp
Labels: enhancement

#290 Task 118
  .gitignore
  src/main/java/org/springframework/samples/volleymate/logro/LogroController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/centros/centroDetails.jsp
  src/main/webapp/WEB-INF/jsp/jugadores/detallesJugador.jsp
  src/main/webapp/WEB-INF/jsp/logro/crearLogro.jsp
  src/main/webapp/WEB-INF/jsp/logro/crearOActualizar.jsp
  src/main/webapp/WEB-INF/jsp/logro/listado.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/main/webapp/WEB-INF/tags/pivotal.tag
Labels: enhancement
